title: Gneisswork
description: A free and open-source web application for field geological and sedimentological core logging
url: https://gneisswork.app
baseurl: ""

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - .venv/
  - .archives/
  - .claude/
  - .git/
  - .github/
  - .gitignore
  - .kiro/
  - .pwlw-sedmob/
  - .pytest_cache/
  - .vscode/
  - instance/
  - sedmob/
  - run.py
